//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryBook.Locales
{
  using System;

  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("VS Code RESX Editor", "1.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  public class Parameters
  {
    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Parameters()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
      get
      {
        if (object.ReferenceEquals(resourceMan, null))
        {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Parameters", typeof(Parameters).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
      get
      {
        return resourceCulture;
      }
      set
      {
        resourceCulture = value;
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Adventure.
    /// </summary>
    public static string Adventure
    {
      get
      {
        return ResourceManager.GetString("Adventure", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Comedy.
    /// </summary>
    public static string Comedy
    {
      get
      {
        return ResourceManager.GetString("Comedy", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Fantasy.
    /// </summary>
    public static string Fantasy
    {
      get
      {
        return ResourceManager.GetString("Fantasy", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Mystery.
    /// </summary>
    public static string Mystery
    {
      get
      {
        return ResourceManager.GetString("Mystery", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to City.
    /// </summary>
    public static string City
    {
      get
      {
        return ResourceManager.GetString("City", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Town.
    /// </summary>
    public static string Town
    {
      get
      {
        return ResourceManager.GetString("Town", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Forest.
    /// </summary>
    public static string Forest
    {
      get
      {
        return ResourceManager.GetString("Forest", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Desert.
    /// </summary>
    public static string Desert
    {
      get
      {
        return ResourceManager.GetString("Desert", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Beach.
    /// </summary>
    public static string Beach
    {
      get
      {
        return ResourceManager.GetString("Beach", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Volcano.
    /// </summary>
    public static string Volcano
    {
      get
      {
        return ResourceManager.GetString("Volcano", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Island.
    /// </summary>
    public static string Island
    {
      get
      {
        return ResourceManager.GetString("Island", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to River.
    /// </summary>
    public static string River
    {
      get
      {
        return ResourceManager.GetString("River", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cat.
    /// </summary>
    public static string Cat
    {
      get
      {
        return ResourceManager.GetString("Cat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Dog.
    /// </summary>
    public static string Dog
    {
      get
      {
        return ResourceManager.GetString("Dog", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Rabbit.
    /// </summary>
    public static string Rabbit
    {
      get
      {
        return ResourceManager.GetString("Rabbit", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Turtle.
    /// </summary>
    public static string Turtle
    {
      get
      {
        return ResourceManager.GetString("Turtle", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Snake.
    /// </summary>
    public static string Snake
    {
      get
      {
        return ResourceManager.GetString("Snake", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Scorpion.
    /// </summary>
    public static string Scorpion
    {
      get
      {
        return ResourceManager.GetString("Scorpion", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Gorilla.
    /// </summary>
    public static string Gorilla
    {
      get
      {
        return ResourceManager.GetString("Gorilla", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Lion.
    /// </summary>
    public static string Lion
    {
      get
      {
        return ResourceManager.GetString("Lion", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Eagle.
    /// </summary>
    public static string Eagle
    {
      get
      {
        return ResourceManager.GetString("Eagle", resourceCulture);
      }
    }
  }
}